services:
  deep-research:
    container_name: deep-research
    build: .
    env_file:
      - .env
    volumes:
      -  ./:/app/
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    command: npm run api:docker
